### ISSUE TITLE
flutter_webview_pro: ^3.0.1+1 

### ISSUE THREAD

**Issue by iosmakerov** [wenzhiming/flutter-plugins#1]
Hey!
I have an application in which I use webview_flutter: ^3.0.1 and it works well (except that files cannot be uploaded to android).
I'm trying to build a project with flutter_webview_pro: ^3.0.1+1 but I get errors and fail to build

What could be the problem and how to fix it?

Android log:
`../../../.pub-cache/hosted/pub.dartlang.org/flutter_webview_pro-3.0.1+1/lib/src/webview.dart:132:23: Error: A value of type 'CupertinoWebView' can't be assigned to a variable of type 'WebViewPlatform?'.
 - 'CupertinoWebView' is from 'package:webview_flutter_wkwebview/src/webview_cupertino.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/webview_flutter_wkwebview-2.7.1/lib/src/webview_cupertino.dart').
 - 'WebViewPlatform' is from 'package:webview_pro_platform_interface/src/platform_interface/webview_platform.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/webview_pro_platform_interface-1.8.1+1/lib/src/platform_interface/webview_platform.dart').
          _platform = CupertinoWebView();
                      ^
../../../.pub-cache/hosted/pub.dartlang.org/flutter_webview_pro-3.0.1+1/lib/src/webview.dart:813:49: Error: A value of type 'WKWebViewCookieManager' can't be assigned to a variable of type 'WebViewCookieManagerPlatform?'.
 - 'WKWebViewCookieManager' is from 'package:webview_flutter_wkwebview/src/wkwebview_cookie_manager.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/webview_flutter_wkwebview-2.7.1/lib/src/wkwebview_cookie_manager.dart').
 - 'WebViewCookieManagerPlatform' is from 'package:webview_pro_platform_interface/src/platform_interface/webview_cookie_manager.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/webview_pro_platform_interface-1.8.1+1/lib/src/platform_interface/webview_cookie_manager.dart').
        WebViewCookieManagerPlatform.instance = WKWebViewCookieManager();
                                                ^

FAILURE: Build failed with an exception.

* Where:
Script '/Users/maker/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 1102

* What went wrong:
Execution failed for task ':app:compileFlutterBuildPaxumDebug'.
> Process 'command '/Users/maker/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 30s
Exception: Gradle task assemblePaxumDebug failed with exit code 1`

iOS log:
`Xcode's output:
↳
    Writing result bundle at path:
    	/var/folders/jk/_w3vb6vd4614wqyw9p7r67w00000gn/T/flutter_tools.QJfwc3/flutter_ios_build_temp_diraogU3U/temporary_xcresult_bundle

    ../../../.pub-cache/hosted/pub.dartlang.org/flutter_webview_pro-3.0.1+1/lib/src/webview.dart:132:23: Error: A value of type 'CupertinoWebView' can't be assigned to a variable of type 'WebViewPlatform?'.
     - 'CupertinoWebView' is from 'package:webview_flutter_wkwebview/src/webview_cupertino.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/webview_flutter_wkwebview-2.7.1/lib/src/webview_cupertino.dart').
     - 'WebViewPlatform' is from 'package:webview_pro_platform_interface/src/platform_interface/webview_platform.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/webview_pro_platform_interface-1.8.1+1/lib/src/platform_interface/webview_platform.dart').
              _platform = CupertinoWebView();
                          ^
    ../../../.pub-cache/hosted/pub.dartlang.org/flutter_webview_pro-3.0.1+1/lib/src/webview.dart:813:49: Error: A value of type 'WKWebViewCookieManager' can't be assigned to a variable of type 'WebViewCookieManagerPlatform?'.
     - 'WKWebViewCookieManager' is from 'package:webview_flutter_wkwebview/src/wkwebview_cookie_manager.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/webview_flutter_wkwebview-2.7.1/lib/src/wkwebview_cookie_manager.dart').
     - 'WebViewCookieManagerPlatform' is from 'package:webview_pro_platform_interface/src/platform_interface/webview_cookie_manager.dart' ('../../../.pub-cache/hosted/pub.dartlang.org/webview_pro_platform_interface-1.8.1+1/lib/src/platform_interface/webview_cookie_manager.dart').
            WebViewCookieManagerPlatform.instance = WKWebViewCookieManager();
                                                    ^
    Failed to package /Users/maker/DEVELOPER/FLUTTER_PROJECTS/mobile_flutter_app.
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order

    Result bundle written to path:
    	/var/folders/jk/_w3vb6vd4614wqyw9p7r67w00000gn/T/flutter_tools.QJfwc3/flutter_ios_build_temp_diraogU3U/temporary_xcresult_bundle`

**Comment by jebstern** [comment]
I have the same issue

**Comment by r6c** [comment]
@wenzhiming I have the same issue

**Comment by wenzhiming** [comment]
Please upgrade to the new version 3.0.1 + 2

**Comment by amdarshini** [comment]
I am also facing same issue. I have an application in which I use webview_flutter: ^3.0.1 and it works well (except that files cannot be uploaded to android).
