### ISSUE TITLE
'Take Photo' or 'Photo Library' change name

### ISSUE THREAD

**Issue by YongSeongLee25** [wenzhiming/flutter-plugins#10]
hello. Is it possible to rename 'Take Photo' and 'Photo Library' when performing file select?

**Comment by uzairmughal3397** [comment]
And is it possible to add only one button "Photo Library"

**Comment by yukidaruma** [comment]
@YongSeongLee25 Actually it's possible.

1. In your Flutter project, navigate to `android/app/src/main/res/values` directory.
2. Create `string.xml` in the directory.
3. Translate text accordingly.
   ```xml
   <resources>
     <string name="take_photo">Take Photo</string>
     <string name="photo_library">Photo Library</string>
     <string name="select_picture">Select File</string>
     <string name="take_pic_need_permission">Taking pictures need you to grant camera permission</string>
   </resources>
   ```
