### ISSUE TITLE
couldn't find the metadata for provider with authority

### ISSUE THREAD

**Issue by rafayrao97** [wenzhiming/flutter-plugins#11]
When I try to click on "Take Photo" button in android,it toast me this error "couldn't find the metadata for provider with authority" ,any solution ?

**Comment by uzairmughal3397** [comment]
Hi did you get any solution?

**Comment by rafayrao97** [comment]
> Hi did you get any solution?

Not yet,I am totally stuck

**Comment by uzairmughal3397** [comment]
Add this in your manifest.
      
      ```
<provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="com.your.applicationid.fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_paths" />
        </provider>
```
and create provider_paths.xml file in xml folder inside res folder and add this in this file

`
<?xml version="1.0" encoding="utf-8"?>
<paths>
    <external-path
        name="external_files"
        path="." />
    <external-files-path
        name="my_images"
        path="Pictures" />
    <cache-path
        name="images"
        path="/" />
</paths>
`

**Comment by uzairmughal3397** [comment]
Create a file provider_paths and add this code in it
![image](https://user-images.githubusercontent.com/35632239/163689994-775e3927-5d1f-41f3-84c6-885ff3e064ef.png)

**Comment by uzairmughal3397** [comment]
And this in your manifest file 
insider application tag

![image](https://user-images.githubusercontent.com/35632239/163690011-510bc95d-8035-48d1-82a5-a4823ff27bb6.png)

**Comment by rafayrao97** [comment]
I did it but was not working for me ,let me try it once again

**Comment by uzairmughal3397** [comment]
Make sure you are using .fileprovider not .provider in manifest

**Comment by rafayrao97** [comment]
sure

**Comment by rafayrao97** [comment]
No brother,still getting same error .

**Comment by rafayrao97** [comment]
> No brother,still getting same error .

Let me share with you my SS

**Comment by rafayrao97** [comment]
![issue1](https://user-images.githubusercontent.com/61781056/163690574-6adb2db6-1f2d-43c9-801c-69e74c87c69c.JPG)

**Comment by rafayrao97** [comment]
![issue2](https://user-images.githubusercontent.com/61781056/163690586-eb968c90-3192-42a0-b4a1-e8b0df91fa62.JPG)

**Comment by rafayrao97** [comment]
Did you add something else other than this code ?

**Comment by uzairmughal3397** [comment]
No bro

**Comment by rafayrao97** [comment]
yes resolved from your code actually it was a space issue there in manifest in android :authorities

Thanks BTW

**Comment by wenzhiming** [comment]
look here  issues #2
