### ISSUE TITLE
Flutter 3.0.0 

### ISSUE THREAD

**Issue by ITApexGroup** [wenzhiming/flutter-plugins#15]
┌─ Flutter Fix ──────────────────────────────────────────────────────────────────────────────────┐
│ Flutter multidex handling is disabled. If you wish to let the tool configure multidex, use the │
│ --multidex flag.                                                                               │
└────────────────────────────────────────────────────────────────────────────────────────────────┘

**Comment by EA-YOUHOU** [comment]
Related to https://github.com/wenzhiming/flutter-plugins/issues/16 ?

**Comment by wenzhiming** [comment]
Please upgrade to the new version flutter_webview_pro: ^3.0.1+3
