### ISSUE TITLE
Couldn't find meta-data for provider...

### ISSUE THREAD

**Issue by MrDiezDOTcom** [wenzhiming/flutter-plugins#2]
Hi

I'm trying to get your plugin to work with my webpage :)

The good news is when I click on my picture button your plugin ask me if I want to use the camera or gallery.

But when I choose camera I got this:

![Capture d’écran 2022-03-31 à 10 35 37](https://user-images.githubusercontent.com/24249215/161037739-281ac87c-aafc-467b-9dd7-2b6e478f7115.png)

I followed (without success) the answer to this thread:
https://stackoverflow.com/questions/56598480/couldnt-find-meta-data-for-provider-with-authority

So I tried to add the "provider" tag to my android/app/src/main/AndroidManifest.xml:

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.flutter_webview_poc">
   <uses-permission android:name="android.permission.INTERNET"/>
   <uses-permission android:name="android.permission.CAMERA"/>

   <application
        android:label="flutter_webview_poc"
        android:icon="@mipmap/ic_launcher"
        android:usesCleartextTraffic="true">

       <provider
           android:name="androidx.core.content.FileProvider"
           android:authorities="com.example.flutter_webview_poc.provider"
           android:exported="false"
           android:grantUriPermissions="true">
           <meta-data
               android:name="android.support.FILE_PROVIDER_PATHS"
               android:resource="@xml/provider_paths" />
       </provider>
       
       ...
```

And I created android/app/src/main/res/xml/provider_paths.xml:

```
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <external-path
        name="external_files"
        path="." />
</paths>
```

But I still have the issue. 

Hint: there is a third suggestion on the main answer to this stackoverflow's thread
but I think it has to be done on the Kotlin side.

Do you have any idea what's happening here ?
Thanks you

**Comment by yy1300326388** [comment]
我有同样的问题，相册可以使用，但是拍照无法使用

**Comment by yy1300326388** [comment]
我的项目是 fileprovider，其中p 是大写，这里是小写，所以出错了，我本地修改一下，重新依赖

**Comment by MrDiezDOTcom** [comment]
> replace `android:authorities="com.example.flutter_webview_poc.provider"` with `android:authorities="${applicationId}.fileprovider"`

THANKS YOU
It worked

I thought that "applicationId" wasn't defined and so I had to replace it with my app id.

@yy1300326388 did you try to add the "provider" tag to the AndroidManifest.xml file and to create res/xml/provider_paths.xml ?

**Comment by yy1300326388** [comment]
> > replace `android:authorities="com.example.flutter_webview_poc.provider"` with `android:authorities="${applicationId}.fileprovider"`
> 
> THANKS YOU It worked
> 
> I thought that "applicationId" wasn't defined and so I had to replace it with my app id.
> 
> @yy1300326388 did you try to add the "provider" tag to the AndroidManifest.xml file and to create res/xml/provider_paths.xml ?

Thank you very much, I solved it here
