### ISSUE TITLE
'webview_flutter_wkwebview/FLTCookieManager.h' file not found i iOS 13 Simulator

### ISSUE THREAD

**Issue by Saikiran24** [wenzhiming/flutter-plugins#7]
/Users/Softwares/flutter/.pub-cache/hosted/pub.dartlang.org/webview_pro_wkwebview-2.7.1+1/ios/Classes/webview-umbrella.h:6:9: 'webview_flutter_wkwebview/FLTCookieManager.h' file not found

**Comment by EA-YOUHOU** [comment]
+1

**Comment by bantunes22** [comment]
The plugin is working properly in Android, but failed to compile in iOS.

**Comment by EA-YOUHOU** [comment]
Waiting for : https://github.com/wenzhiming/flutter-plugins/pull/5

**Comment by Slihao** [comment]
+1

**Comment by EA-YOUHOU** [comment]
up

**Comment by wenzhiming** [comment]
Please upgrade to the new version 3.0.1 + 3
